version: '3.1'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=Kris
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=db
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql



